# Generated by Django 2.0.13 on 2019-11-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='詳細')),
                ('status', models.CharField(choices=[('OPEN', '新規'), ('WIP', '作業中'), ('PEND', '保留'), ('DONE', '完了')], default='OPEN', max_length=4, verbose_name='ステータス')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
