# Generated by Django 2.0.13 on 2019-11-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.TextField(max_length=2000, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('新規', '新規'), ('作業中', '作業中'), ('保留', '保留'), ('完了', '完了')], default='新規', max_length=4, verbose_name='ステータス'),
        ),
    ]
